<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NLHDotNetTrainingBatch3.ProductnSaleDatabase\NLHDotNetTrainingBatch3.ProductnSaleDatabase.csproj" />
    <ProjectReference Include="..\RestAPI\RestAPI.csproj" />
  </ItemGroup>

</Project>
